{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "octovault.fullname" . }}
  labels:
    {{- include "octovault.labels" . | nindent 4 }}
rules:
  # CRDs: OctoRepository / OctoVault
  - apiGroups: ["octovault.it"]
    resources:
      - octorepositories
      - octorepositories/status
      - octorepositories/finalizers
      - octovaults
      - octovaults/status
      - octovaults/finalizers
    verbs: ["get","list","watch","create","update","patch","delete"]
  # Core: Secrets, ConfigMaps, Events
  - apiGroups: [""]
    resources: ["secrets","configmaps"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch"]
{{- end }}
